# installs the full set of packages used by this project's various scripts
package.install(shiny)
package.install(dplyr)
package.install(tidyr)
package.install(ggplot2)
package.install(plotly)
package.install(ggrepel)
package.install(DT)
package.install(data.table)
package.install(readr)
package.install(openxlsx)
package.install(stringr)
package.install(biomaRt)
package.install(BiocManager)
package.install(janitor)