---
title: "linkTables"
format: html
---

```{r}
library(data.table)
library(dplyr)
library(readr)
library(stringr)
```

```{r}
# change base_path here if necessary
base_path = "~/Documents/GitHub/MousePhenotypeGroup13/"

# get merged analyses table
merged_path = str_c(base_path, "output/combined_data.csv")
merged_df = fread(merged_path)
head(merged_df, 3)
```

```{r}
# select only the gene-relevant columns
genes_df = unique(merged_df[, c(1,2)]) # reduce to only unique columns
head(genes_df, 3)
```

```{r}
# check how many repeats exist in merged analyses table 
nrow(merged_df) - nrow(genes_df)
```

```{r}
# lowercase the columns to distinguish from merge analysis table
colnames(genes_df) = tolower(colnames(genes_df))
head(genes_df, 3)
```

```{r}
# d_path = str_c(base_path, "output/diseases_cleaned.csv")
# disease_df = fread(d_path)
# head(disease_df)
```

```{r}
# nrow(genes_df)
# length(unique(genes_df$gene_symbol))
```


```{r}
# uniq_mgi_ids = unique(disease_df$mouse_mgi_id)
# for (i in 1:length(uniq_mgi_ids)) {
#   if (!(uniq_mgi_ids[i] %in% (genes_df$gene_accession_id))) {
#     curr = list(uniq_mgi_ids[i], NA) # using c() treats NA poorly
#     genes_df = rbind(genes_df, curr)
#   }
# }
# 
# tail(genes_df)
```

```{r}
# nrow(genes_df)
# length(unique(genes_df$gene_symbol))
# length(uniq_mgi_ids)
```


```{r}
# write out the genes table
output_path = str_c(base_path, "output/genes.csv")
fwrite(genes_df, output_path)
```
