# installs the full set of packages used by this project's various scripts
install.packages(shiny)
install.packages(dplyr)
install.packages(tidyr)
install.packages(ggplot2)
install.packages(plotly)
install.packages(ggrepel)
install.packages(DT)
install.packages(data.table)
install.packages(readr)
install.packages(openxlsx)
install.packages(stringr)
install.packages(biomaRt)
install.packages(BiocManager)
install.packages(janitor)